name: Upload dSYM Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload dSYMs to Datadog
        uses: DataDog/upload-dsyms-github-action@main
        with:
          api_key: ${{ secrets.DATADOG_API_KEY }}
          site: datadoghq.com
          dry_run: false
          dsym_paths: |
            src/__tests__/fixtures/test.zip